manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/cdc-mkb/zmk/tree/mouse-pim447
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
